name: OCP LOCK Spec CI

on:
  pull_request:
    paths: 
      - doc/ocp_lock/**

jobs:
  ocp-lock-render:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trustedcomputinggroup/pandoc:latest
    name: Render OCP LOCK PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout Template dependencies
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          repository: "opencomputeproject/ocp-spec-tools"
          ref: "45d41cc0d58edccf49d961443d52af4291db7735"
          # The underlying Tex and templates assume this exists under the "extra" folder.
          path: "doc/ocp_lock/extra"

      - name: Render OCP LOCK PDF
        run: |
          (cd doc/ocp_lock &&
          /usr/bin/build.sh \
          --crossref=tcg \
          --csl extra/ocp-pandoc-resources/ieee.csl \
          --nogitversion \
          --template extra/ocp-pandoc-resources/pdf/ocp.tex \
          --template_html extra/ocp-pandoc-resources/html/ocp.html.template \
          --html_stylesheet extra/ocp-pandoc-resources/html/style.css \
          --html_stylesheet extra/ocp-pandoc-resources/html/github-markdown.css \
          --resourcedir extra/ocp-pandoc-resources/pdf \
          --pdf OCP-LOCK-Specification-${{ github.head_ref }}-${{ github.sha }}.pdf lock_spec.ocp)

      - name: Upload PDF to PR
        uses: actions/upload-artifact@master
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: OCP LOCK PDF
          path: doc/ocp_lock/OCP-LOCK-Specification-${{ github.head_ref }}-${{ github.sha }}.pdf

      - name: Render OCP LOCK HTML
        run: |
          (cd doc/ocp_lock &&
          /usr/bin/build.sh \
          --crossref=tcg \
          --csl extra/ocp-pandoc-resources/ieee.csl \
          --nogitversion \
          --template extra/ocp-pandoc-resources/pdf/ocp.tex \
          --template_html extra/ocp-pandoc-resources/html/ocp.html.template \
          --html_stylesheet extra/ocp-pandoc-resources/html/style.css \
          --html_stylesheet extra/ocp-pandoc-resources/html/github-markdown.css \
          --resourcedir extra/ocp-pandoc-resources/pdf \
          --html OCP-LOCK-Specification-${{ github.head_ref }}-${{ github.sha }}.html lock_spec.ocp)

      - name: Upload HTML to PR
        uses: actions/upload-artifact@master
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: OCP LOCK HTML
          path: doc/ocp_lock/OCP-LOCK-Specification-${{ github.head_ref }}-${{ github.sha }}.html
